events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-service:5173;
        }

        location /auth/ {
            proxy_pass http://auth-service:8000/;
        }

        location /ledger/ {
            proxy_pass http://ledger-service:8000/;
        }
    }
}
